CREATE DATABASE IF NOT EXISTS ESC_SFDC_TO_DB; 

CREATE TABLE IF NOT EXISTS ESC_SFDC_TO_DB.Contact(
  Id VARCHAR(300),
  Salutation VARCHAR(30),
  Name VARCHAR(300),
  Mobile VARCHAR(30),
  Email VARCHAR(350),
  Phone VARCHAR(30),
  Fax VARCHAR(30),
  AccountId VARCHAR(300),
  Title VARCHAR(300),
  Department VARCHAR(300),
  PRIMARY KEY (`Id`)
);